name: Lex-Impact-FE CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18
           

      - name: Install dependencies
        run: npm install
        working-directory: ./lex-impact

      - name: Lint
        run: npm run lint 
        working-directory: ./lex-impact

      - name: Build Next.js app
        run: npm build
        working-directory: ./lex-impact

      - name: Run tests
        run: npm test 
        working-directory: ./lex-impact

      - name: ✅ All checks passed
        run: echo "Ready to merge!"
